// <auto-generated />
using System;
using Admin.Erp.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Admin.Erp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240922152630_PermissoesRotasIdMigration")]
    partial class PermissoesRotasIdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Admin.Erp.Domain.Entities.AcessoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ExpiracaoDoTokenEsqueceuSenha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TokenEsqueceuSenha")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Bloqueado");

                    b.HasIndex("TokenEsqueceuSenha");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("AcessosUsuarios");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Premium")
                        .HasColumnType("boolean");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Global.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Icone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Premium")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Ordem");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Global.MenuRota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuRotas");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.PerfilUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("PerfilUsuarios");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.PerfilUsuarioMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerfilUsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MenuId")
                        .IsUnique();

                    b.HasIndex("PerfilUsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilUsuarioMenus");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.PerfilUsuarioMenuRota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MenuRotaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerfilUsuarioMenuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MenuRotaId");

                    b.HasIndex("PerfilUsuarioMenuId");

                    b.ToTable("PerfilUsuarioMenuRotas");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DataDeNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PerfilUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<NpgsqlTsVector>("Search")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "portuguese")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Nome", "Cpf" });

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Nome");

                    b.HasIndex("PerfilUsuarioId");

                    b.HasIndex("Search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.AcessoUsuario", b =>
                {
                    b.HasOne("Admin.Erp.Domain.Entities.Usuario", "Usuario")
                        .WithOne("AcessoUsuario")
                        .HasForeignKey("Admin.Erp.Domain.Entities.AcessoUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Global.MenuRota", b =>
                {
                    b.HasOne("Admin.Erp.Domain.Entities.Global.Menu", "Menu")
                        .WithMany("MenuRotas")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.PerfilUsuarioMenu", b =>
                {
                    b.HasOne("Admin.Erp.Domain.Entities.Global.Menu", "Menu")
                        .WithOne("PerfilUsuarioMenu")
                        .HasForeignKey("Admin.Erp.Domain.Entities.PerfilUsuarioMenu", "MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Admin.Erp.Domain.Entities.PerfilUsuario", "PerfilUsuario")
                        .WithOne("PerfilUsuarioMenu")
                        .HasForeignKey("Admin.Erp.Domain.Entities.PerfilUsuarioMenu", "PerfilUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("PerfilUsuario");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.PerfilUsuarioMenuRota", b =>
                {
                    b.HasOne("Admin.Erp.Domain.Entities.Global.MenuRota", "MenuRota")
                        .WithMany()
                        .HasForeignKey("MenuRotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admin.Erp.Domain.Entities.PerfilUsuarioMenu", "PerfilUsuarioMenu")
                        .WithMany("PerfilUsuarioMenuRota")
                        .HasForeignKey("PerfilUsuarioMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuRota");

                    b.Navigation("PerfilUsuarioMenu");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Admin.Erp.Domain.Entities.PerfilUsuario", "PerfilUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilUsuario");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Global.Menu", b =>
                {
                    b.Navigation("MenuRotas");

                    b.Navigation("PerfilUsuarioMenu")
                        .IsRequired();
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.PerfilUsuario", b =>
                {
                    b.Navigation("PerfilUsuarioMenu")
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.PerfilUsuarioMenu", b =>
                {
                    b.Navigation("PerfilUsuarioMenuRota");
                });

            modelBuilder.Entity("Admin.Erp.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AcessoUsuario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
